spring.application.name=api-str-innovation

spring.datasource.url=jdbc:postgresql://ep-young-sun-a4ol5e8m.us-east-1.aws.neon.tech:5432/strdb
spring.datasource.username=neondb_owner
spring.datasource.password=9frnXYg4luVc
