spring.application.name=api-str-innovation

server.port=2023
spring.datasource.url=jdbc:postgresql://ep-solitary-breeze-a52f3tn2.us-east-2.aws.neon.tech:5432/strdb
spring.datasource.username=neondb_owner
spring.datasource.password=Y6olcfXtae2j