spring.application.name=api-str-innovation

server.port=2023
spring.datasource.url=jdbc:postgresql://ep-fragrant-mountain-a59qrml1-pooler.us-east-2.aws.neon.tech/str?sslmode=require
spring.datasource.username=str_owner
spring.datasource.password=npg_H7Z8omAEesXY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

api.security.token.secret=${JWT_SECRET:my-secret-key}