CREATE TABLE checklist (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tire BOOLEAN NOT NULL,
    spare_tire VARCHAR(100) NOT NULL,
    kilometers_number NUMERIC NOT NULL,
    fuel_level NUMERIC NOT NULL,
    oil_level NUMERIC NOT NULL,
    water_level NUMERIC NOT NULL,
    suspension BOOLEAN NOT NULL,
    brakes VARCHAR(100) NOT NULL,
    lights VARCHAR(100) NOT NULL,
    glasses BOOLEAN NOT NULL,
    windshield_wipers BOOLEAN NOT NULL,
    rearview BOOLEAN NOT NULL,
    headlight BOOLEAN NOT NULL,
    taillight BOOLEAN NOT NULL,
    frontIndicator BOOLEAN NOT NULL,
    indicator BOOLEAN NOT NULL,
    domeLight BOOLEAN NOT NULL,
    licensePlateLight BOOLEAN NOT NULL,
    tirePressure VARCHAR(100) NOT NULL,
    jack VARCHAR(100) NOT NULL,
    toolbox VARCHAR(100) NOT NULL,
    documentation VARCHAR(100) NOT NULL,
    observation_notes VARCHAR(255) NULL,
    created_dt DATE NOT NULL,
    edited_dt DATE NULL,
    vehicle_fk UUID,
    FOREIGN KEY (vehicle_fk) REFERENCES vehicle(id)
);