CREATE TABLE checklist (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tire VARCHAR(100) NOT NULL,
    spare_tire VARCHAR(100) NOT NULL,
    kilometers_number NUMERIC NOT NULL,
    fuel_level NUMERIC NOT NULL,
    oil_level NUMERIC NOT NULL,
    water_level NUMERIC NOT NULL,
    suspension VARCHAR(100) NOT NULL,
    brakes VARCHAR(100) NOT NULL,
    lights VARCHAR(100) NOT NULL,
    glasses VARCHAR(100) NOT NULL,
    windshield_wipers VARCHAR(100) NOT NULL,
    jack VARCHAR(100) NOT NULL,
    toolbox VARCHAR(100) NOT NULL,
    documentation VARCHAR(100) NOT NULL,
    observation_notes VARCHAR(255) NULL,
    created_dt DATE NOT NULL,
    edited_dt DATE NULL,
    vehicle_fk UUID,
    FOREIGN KEY (vehicle_fk) REFERENCES vehicle(id)
);