CREATE TABLE checklist (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tire VARCHAR(100) NOT NULL,
    license_plate_number VARCHAR(100) NOT NULL,
    spare_tire VARCHAR(100) NOT NULL,
    kilometers_number VARCHAR(100) NOT NULL,
    fuel_level VARCHAR(100) NOT NULL,
    oil_level VARCHAR(100) NOT NULL,
    water_level VARCHAR(100) NOT NULL,
    suspension VARCHAR(100) NOT NULL,
    brakes VARCHAR(100) NOT NULL,
    lights VARCHAR(100) NOT NULL,
    glasses VARCHAR(100) NOT NULL,
    windshield_wipers VARCHAR(100) NOT NULL,
    jack VARCHAR(100) NOT NULL,
    toolbox VARCHAR(100) NOT NULL,
    documentation VARCHAR(100) NOT NULL,
    observation_notes VARCHAR(255) NULL,
    created_dt TIMESTAMP NOT NULL,
    edited_dt TIMESTAMP NULL,
    vehicle_fk UUID,
    FOREIGN KEY (vehicle_fk) REFERENCES vehicle(id)
);